# conda env create -f environment.yml
name: atmodat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - compliance-checker==4.3.2
  - cfunits
  - udunits2
  - pytest
  - git
  - gitpython
